spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 642838857127-qslf05co1hs10ur1a1tfa655o2krtb3c.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile